version: "3.4"

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tempcalc
    ports:
      - "6969:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: always